import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/shared/components/nav/Navbar";
import { ViewTransitions } from "next-view-transitions";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased h-screen pt-20"
          )}
        >
          <Navbar />
          {children}
          <ToastContainer />
        </body>
      </html>
    </ViewTransitions>
  );
}
